@startuml
'https://plantuml.com/class-diagram

class Student {
    -id: Integer
    -last_name: String
    -first_name: String
    -father_name: String
    -phone: String
    -telegram: String
    -email: String
    -git: String
    +{static}valid_name?(String): Boolean
    +{static}valid_phone?(String): Boolean
    +{static}valid_profile_name?(String): Boolean
    +{static}valid_email?(String): Boolean
    +{static}from_json_str(String): Student
    +initialize(String, String, String, Hash)
    +(all accessors)
    +valid_contacts?(): Boolean
    +valid_git?(): Boolean
    +valid?(): Boolean
    +set_contacts(Hash)
    +short_contact(): String
    +short_name(): String
    +short_info(): String
    +to_s(): String
    +to_json_str(): String
}

@enduml